export const caseStudy2Data = {
  c1: {
    imgURL: "/Images/caseStudy2/caseStudyBTC.png",
    head: "BORG Buyback",
    headColor: "#4C4C4C",
    content: "To boost our ecosystem, every week we buy back BORG on the market using the fees generated by the SwissBorg Earn program. The amount we buy is based on the Community Index - the higher the Index, the more we buy!.", 
    content_text_color: "",

    flexDirection: "row-reverse",
    bgColor: "#FFF",
    btn: "Tell me more",
    btn_bgColor: "#007CD7",
  },

  c2: {
    imgURL: "/Images/caseStudy2/caseStudy2Shield.png",
    head: "BORG Protect & Choose",
    headColor: "#4C4C4C",
    content: "A percentage of the revenue earned from exchange fees is used to buy back BORG tokens. Then, every month, the BORG holders can decide how the tokens will be used.",
    content_text_color: "",

    flexDirection: "row-reverse",
    bgColor: "#FFF",
    btn: "Learn more",
    btn_bgColor: "#007CD7",
  },

  c3: {
    imgURL: "/Images/caseStudy2/BTC_lock.png",
    head: "Locking",
    headColor: "#FFA200",
    content:"Users can lock their BORG tokens for a pre-defined period, reducing the available supply and increasing scarcity while enjoying Premium benefits..",
    content_text_color: "#FFA200",

    flexDirection: "row",
    bgColor: "#FFF7EA",
    btn: "More BORG metrics",
    btn_bgColor: "#FFA200",
  },

  c4: {
    imgURL: "/Images/caseStudy2/fourGems.png",
    head: "Premium Benefits",
    headColor: "#4C4C4C",
    content: "By holding BORG tokens, Premium users show their confidence and trust in the BORG's long term value while benefiting from lower exchange fees on multiple cryptocurrencies",
    content_text_color: "",

    flexDirection: "row-reverse",
    bgColor: "#FFF",
    btn: "Become a premium member",
    btn_bgColor: "#FFA200",
  },

  c5: {
    imgURL: "/Images/caseStudy2/caseStudy2Search.png",
    head: "What is Self Verification?",
    headColor: "#4C4C4C",
    content:
      "Using our simple verification  tool based on well-established Merkle tree cryptographic techniques you can verify the correctness of your account balance and proper inclusion of your assets in the company’s total liabilities.",
    content_text_color: "",

    flexDirection: "row",
    bgColor: "#FFF",
    btn: "Learn more",
    btn_bgColor: "#007CD7",
  },

  c6: {
    imgURL: "/Images/caseStudy2/BTC_lock.png",
    head: "Diversify risk in one tap",
    headColor: "#4C4C4C",
    content:
      "95% of crypto projects fail. Putting all your bets on one token is highly risky. Instead broaden your horizons and invest across your favourite trends & themes, all with just one tap.",
    content_text_color: "",

    flexDirection: "row",
    bgColor: "#FFF",
    btn: "Tell me more",
    btn_bgColor: "#007CD7",
  },

  c7: {
    imgURL: "/Images/caseStudy2/BTC_lock.png",
    head: "Diversify risk in one tap",
    headColor: "#4C4C4C",
    content:
      "95% of crypto projects fail. Putting all your bets on one token is highly risky. Instead broaden your horizons and invest across your favourite trends & themes, all with just one tap.",
    content_text_color: "",

    flexDirection: "row",
    bgColor: "#FFF",
    btn: "Tell me more",
    btn_bgColor: "#007CD7",
  },
};
