export const exploreThematicsData = {
  thematic1: {
    backgroundColor: "./Images/exploreThematics/bg1.png",
    logo: "./Images/exploreThematics/thematics-logo-1.png",
    name: "Golden",
    desc: "Discover how to navigate the market cycles confidently with our algorithm-driven blend of Bitcoin & Gold.",
    icons: "./Images/exploreThematics/small-icons-1.png",
    coins: "2 coins",
    btns: "Learn More",
  },
  thematic2: {
    backgroundColor: "./Images/exploreThematics/bg2.png",
    logo: "./Images/exploreThematics/thematics-logo-2.png",
    name: "Best Blockchains",
    desc: "The future of finance is built on Blockchains. Dive into the heart of crypto and find out how to stay at the front of this revolution.",
    icons: "./Images/exploreThematics/small-icons-2.png",
    coins: "13 coins",
    btns: "Learn More",
  },
  thematic3: {
    backgroundColor: "./Images/exploreThematics/bg3.png",
    logo: "./Images/exploreThematics/thematics-logo-3.png",
    name: "Banter Bundle",
    desc: "From CNBC’s Crypto Trader to one of the most viral Crypto Social Media Channels, catch the next bull trend alongside Crypto Banter and their top picks.",
    icons: "./Images/exploreThematics/small-icons-3.png",
    coins: "2 coins",
    btns: "Coming Soon",
  },
  thematic1: {
    backgroundColor: "linear-gradient(270deg, #364053 0%, #191E29 100%)",
    logo: "./Images/exploreThematics/thematics-logo-4.png",
    name: "You decide!",
    desc: "Tell us what you'd like to see next and join us in making the most purposeful Thematics accessible to everybody.",
    icons: "./Images/exploreThematics/small-icons-1.png",
    coins: "2 coins",
    btns: "Add your suggestion",
  },
};
