export const headnImgData = {
  fiatCrypto: {
    heading: "Go from Fiat to Crypto in an instant!",
    para: "Connect to Binance, HitBTC, LMAX, Kraken, Bitfinex, Orca and Phoenix exchanges and get the best liquidity and rates in seconds.",
    imgURL: "./Images/headnImg/fiatCrypto.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "",
    btnDisplay: "none",
    btnbgColor: "",
    btnTxtColor: "",
  },
  Basket: {
    heading: "More than a basket of tokens",
    para: "Strengthen your investments with the most promising crypto themes.",
    imgURL: "./Images/headnImg/basket.png",
    bgColor: "linear-gradient(180deg, #004A81 0%, #007CD7 100%)",
    headParaTxtColor: "#FFF",
    btnctn: "Get Started",
    btnDisplay: "flex",
    btnbgColor: "#FFA200",
    btnTxtColor: "#FFF",
  },
  appAssets: {
    heading: "SwissBorg app supported assets",
    para: "The SwissBorg app provides support for different cryptocurrencies. Watch this space for updates as we strive to bring you more listings.",
    imgURL: "./Images/headnImg/appAsset.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "",
    btnDisplay: "none",
    btnbgColor: "",
    btnTxtColor: "",
  },
  accountAnalysis: {
    heading: "Useful Account Analysis at the tap of a finger",
    para: "Portfolio Visualizer, a free tool, provides in-depth investment analysis and statistics in an easy-to-understand format.",
    imgURL: "./Images/headnImg/accountAnalysis.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "",
    btnDisplay: "none",
    btnbgColor: "",
    btnTxtColor: "",
  },
  swissBorgEarn: {
    heading: "Earn crypto your way with SwissBorg Earn",
    para: "Investors aren’t one-size-fits-all, so why is your yield? Generate the right yield for you with SwissBorg Earn.",
    imgURL: "./Images/headnImg/swissborgearn.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "Notify Me",
    btnDisplay: "flex",
    btnbgColor: "#01C38D",
    btnTxtColor: "#FFF",
  },
  topUp: {
    heading: "Top Up and invest in seconds!",
    para: "You can now fund your account using your card and start buying cryptos. It’s fast, secure and EASY!",
    imgURL: "./Images/headnImg/topUp.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "Notify Me",
    btnDisplay: "flex",
    btnbgColor: "#01C38D",
    btnTxtColor: "#FFF",
  },
  smartInvestment: {
    heading: "Make smart investment decisions with the help of AI",
    para: "Automated crypto asset analysis will boost your investment intelligence.",
    imgURL: "./Images/headnImg/smartInvestment.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "",
    btnDisplay: "none",
    btnbgColor: "",
    btnTxtColor: "",
  },
  autoInvest: {
    heading: "Automate your investments",
    para: "Wealth building requires patience, knowledge and discipline. What if all it took was just one good start?  Say goodbye to worries! Unlock your wealth potential with Auto- Invest today.",
    imgURL: "./Images/headnImg/autoInvest.png",
    bgColor: "none",
    headParaTxtColor: "#4C4C4C",
    btnctn: "Get Started",
    btnDisplay: "flex",
    btnbgColor: "#FFA200",
    btnTxtColor: "#FFF",
  },
};
