name: CI, CD, CT for orchestrator-portal UI

env:
  ENVIRONMENT: dev
  SERVICE_CODE: mobius-marketing-website
  ARTIFACT_RETENTION_DAYS: 10
  CODE_PATH: /home/runner/work/mobius-marketing-website/mobius-marketing-website
  DEPLOYMENT_PLATFORM: do
  
# Events
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ] 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      deploymentPlatform: ${{ steps.init.outputs.deploymentPlatform }}

    steps:
      - name: Environment variables to output
        id: init
        run: |
          echo "deploymentPlatform=${{ env.DEPLOYMENT_PLATFORM }}" >> $GITHUB_OUTPUT

  RUN_ON_DO:

     name: RUN_ON_DO
     needs: build
     runs-on: ubuntu-latest

     if: needs.build.outputs.deploymentPlatform == 'do'

     steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Unshallow the checkout
        run: |
          git fetch --prune --unshallow --tags
          git tag --list

      - name: Install dependencies
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm i -f
        
      - name: build project
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          CI=false npm run build
        
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.NEXUSCONNECTS_WEBSITE_HOST }}
          username: ${{ secrets.NEXUSIOUSERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "build/*"
          target: /var/www/dev/
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.NEXUSCONNECTS_WEBSITE_HOST }}
          username: ${{ secrets.NEXUSIOUSERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: ls -lrth /var/www/dev/ && mv /var/www/dev/build/* /var/www/dev/
